package httpoi

const (
	StatusContinue           = "100 Continue"
	StatusSwitchingProtocols = "101 Switching Protocols"

	StatusOK                   = "200 OK"
	StatusCreated              = "201 Created"
	StatusAccepted             = "202 Accepted"
	StatusNonAuthoritativeInfo = "203 Non-Authoritative Information"
	StatusNoContent            = "204 No Content"
	StatusResetContent         = "205 Reset Content"
	StatusPartialContent       = "206 Partial Content"

	StatusMultipleChoices   = "300 Multiple Choices"
	StatusMovedPermanently  = "301 Moved Permanently"
	StatusFound             = "302 Found"
	StatusSeeOther          = "303 See Other"
	StatusNotModified       = "304 Not Modified"
	StatusUseProxy          = "305 Use Proxy"
	StatusTemporaryRedirect = "307 Temporary Redirect"

	StatusBadRequest                   = "400 Bad Request"
	StatusUnauthorized                 = "401 Unauthorized"
	StatusPaymentRequired              = "402 Payment Required"
	StatusForbidden                    = "403 Forbidden"
	StatusNotFound                     = "404 Not Found"
	StatusMethodNotAllowed             = "405 Method Not Allowed"
	StatusNotAcceptable                = "406 Not Acceptable"
	StatusProxyAuthRequired            = "407 Proxy Authentication Required"
	StatusRequestTimeout               = "408 Request Timeout"
	StatusConflict                     = "409 Conflict"
	StatusGone                         = "410 Gone"
	StatusLengthRequired               = "411 Length Required"
	StatusPreconditionFailed           = "412 Precondition Failed"
	StatusRequestEntityTooLarge        = "413 Request Entity Too Large"
	StatusRequestURITooLong            = "414 Request URI Too Long"
	StatusUnsupportedMediaType         = "415 Unsupported Media Type"
	StatusRequestedRangeNotSatisfiable = "416 Requested Range Not Satisfiable"
	StatusExpectationFailed            = "417 Expectation Failed"
	StatusTeapot                       = "418 I'm a teapot"

	StatusInternalServerError     = "500 Internal Server Error"
	StatusNotImplemented          = "501 Not Implemented"
	StatusBadGateway              = "502 Bad Gateway"
	StatusServiceUnavailable      = "503 Service Unavailable"
	StatusGatewayTimeout          = "504 Gateway Timeout"
	StatusHTTPVersionNotSupported = "505 HTTP Version Not Supported"

	statusPreconditionRequired          = "428 Precondition Required"
	statusTooManyRequests               = "429 Too Many Requests"
	statusRequestHeaderFieldsTooLarge   = "431 Request Header Fields Too Large"
	statusNetworkAuthenticationRequired = "511 Network Authentication Required"
)